WIP/feature-requirement6-buyer
vinigracindo/mercado-fresco-stranger-strings pull request #6
Opened 2022-06-03 19:07 UTC by zurcje

É necessário que o Comprador(Buyer) seja composto por:

id: identificador de recurso
card_number_id: identificador de funcionário idem DNI
first_name: nomes de funcionários
ast_name: sobrenome do funcionário

2022-06-06 13:30 UTC, sgabriel99 commented on internal/domains/buyer/BuyerRepository.go
> +func createId() int64 {
Essa função ira gerar ID duplicados.

Motivo: Como ele pega o tamanho do array, caso seja excluido algum elemento, o retorno será um ID que ja existe

Como replicar:
- Crie alguns Usuários
- Apague os primeiros
- Crie outros Usuários
- Liste todos os Usuários

2022-06-06 13:46 UTC, sgabriel99 commented on internal/domains/buyer/BuyerService.go
> +	buyer, err := s.repository.Store(id, cardNumberId, firstName, lastName)
Não é necessário passar o ID, a camada de repository resolve essa questão

2022-06-06 13:48 UTC, sgabriel99 commented on internal/domains/buyer/BuyerRepository.go
> +	return nil, fmt.Errorf("não foi possível alterar, id %d não encontrado", id)
Mensagem de erro em português

2022-06-06 13:49 UTC, sgabriel99 commented on internal/domains/buyer/BuyerRepository.go
> +	return nil, fmt.Errorf("o comprador do id %d não foi encontrado", id)
Mensagem de erro em português

2022-06-06 13:57 UTC, sgabriel99 requested changes
Esta show, corrigir apenas a parte do ID, e como sugestão trocar as mensagem de erro para inglês

2022-06-06 14:11 UTC, katiellyfeitosa requested changes

2022-06-06 14:11 UTC, katiellyfeitosa commented on internal/domains/buyer/BuyerModel.go
> +	CardNumberId int64  `json:"cardNumberId"`
Na documentação do requisito o exemplo das tags json estão com o _. Exemplo: "card_number_id"

2022-06-06 14:11 UTC, katiellyfeitosa commented on cmd/server/controllers/BuyerController.go
> +			ctx.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
No caso do create nao precisamos retornar 404 (not found), o ideal  é passar o 409 (conflict), por já existir.

2022-06-06 14:11 UTC, katiellyfeitosa commented on cmd/server/controllers/BuyerController.go
> +		buyer, err := c.service.Update(req.Id, req.CardNumberId, req.FirstName, req.LastName)
Por ser um patch o ideal é não alterar todos os campos

2022-06-06 14:11 UTC, katiellyfeitosa commented on cmd/server/controllers/BuyerController.go
> +		buyer, err := c.service.Update(req.Id, req.CardNumberId, req.FirstName, req.LastName)
Criar um request struct próprio para o patch, pq se utilizar esse existente, vai obrigar passar todos os campos.

2022-06-06 20:46 UTC, vinigracindo approved these changes

2022-06-06 20:47 UTC, katiellyfeitosa approved these changes

2022-06-07 12:36 UTC, sgabriel99 approved these changes

2022-06-07 13:12 UTC, merged