Feature/requirement3/database implementation
vinigracindo/mercado-fresco-stranger-strings pull request #79
Opened 2022-06-28 18:02 UTC by katiellyfeitosa

- Implementação do database
- Ajustes nos tipos dos campos de acordo com o diagrama

2022-07-01 18:14 UTC, vinigracindo reviewed
Adicionei uma recomendação e um comentário em um possível erro de SQL no teste de delete.

2022-07-01 18:14 UTC, vinigracindo commented on internal/section/repository/mariadb/queries.go
> +	SQLGetAllSection = "SELECT  * FROM sections"
Recomendação: Evitar o uso de * porque pode ocasionar erros futuros na função Scan do Repository quando houver alterações na tabela do banco de dados. Por exemplo, se adicionarem mais colunas a tabela Section no futuro, o * não garante trazer na ordem que você utiliza no Scan.

2022-07-01 18:14 UTC, vinigracindo commented on internal/section/repository/mariadb/repository_test.go
> +		mock.ExpectExec(regexp.QuoteMeta(repository.SQLDeleteSection)).
A query está correta? Você usou repository.SQLDeleteSection ao invés de repository.SQLUpdateCurrentCapacitySection.

2022-07-01 18:18 UTC, vinigracindo requested changes
Adicionei uma recomendação e um possível erro no teste do update no repository. Você usou a query do delete em um dos casos de teste.

2022-07-01 21:53 UTC, martadrozsa commented on internal/section/repository/mariadb/repository_test.go
> +
Sugestão, será que não precisa ter um assert.Equal? Para comparar se deu certo a atualização

2022-07-03 20:41 UTC, martadrozsa commented on internal/section/repository/mariadb/repository_test.go
> +	t.Run("should return all sections", func(t *testing.T) {
Sugestão: em todos os t.Run iniciar a frase sobre o que o teste faz com: "get_all_ok: should return all sections" 
Sugestão também para os demais t.Run

2022-07-03 21:20 UTC, martadrozsa approved these changes
Aprovado!

2022-07-04 12:31 UTC, katiellyfeitosa commented on internal/section/repository/mariadb/repository_test.go
> +
Nesse caso não consigo, pq estou mocando o  newResult, que retorna o lastInsertId e affectRows:  WillReturnResult(sqlmock.NewResult(0, 1)) e não o resultado em si :/

2022-07-04 12:47 UTC, vinigracindo approved these changes

2022-07-04 12:53 UTC, martadrozsa approved these changes
Aprovado! 🚀

2022-07-04 13:17 UTC, merged